import { useEffect } from "react";
import Head from "next/head";
import * as THREE from "three";
import SceneInit from "../lib/SceneInit";
import vertex from "../shaders/vertex.glsl";
import fragment from "../shaders/fragment.glsl";
import styles from "../styles/Home.module.scss";

export default function Home() {
    useEffect(() => {
        console.log(vertex);

        const canvas = new SceneInit("webgl");

        canvas.initialize();
        canvas.animate();

        const geometry = new THREE.PlaneGeometry(1, 1, 500, 500);
        const material = new THREE.ShaderMaterial({
            wireframe: true,
            vertexShader: vertex,
            fragmentShader: fragment,
        });
        const boxMesh = new THREE.Mesh(geometry, material);

        canvas.scene.add(boxMesh);
    }, []);

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <canvas id="webgl" />
            </main>
        </div>
    );
}
